apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd   # Argo CD's namespace
spec:
  project: default

  source:
    repoURL: https://github.com/EladPress/jenkins-charts-temp.git
    targetRevision: master
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
